from lib.Windows.variables import custom_item_type_lookup as Windows
from lib.Unix.variables import custom_item_type_lookup as Unix
from lib.audit_types import *

custom_item_type_lookup = {**Windows, **Unix}
value_type_lookup = {
    "POLICY_TEXT":POLICY_TEXT,
    "POLICY_DWORD":POLICY_DWORD,
    "POLICY_SET":POLICY_SET,
    "POLICY_MULTI_TEXT":POLICY_MULTI_TEXT,
    "POLICY_DAY":POLICY_DAY,
    "POLICY_KBYTE":POLICY_KBYTE,
    "AUDIT_SET":AUDIT_SET,
    "DRIVER_SET":DRIVER_SET,
    "LDAP_SET":LDAP_SET,
    "LOCKEDID_SET":LOCKEDID_SET,
    "SMARTCARD_SET":SMARTCARD_SET,
    "LOCALACCOUNT_SET":LOCALACCOUNT_SET,
    "NTLMSSP_SET":NTLMSSP_SET,
    "LANMAN_SET":LANMAN_SET,
    "LDAPCLIENT_SET":LDAPCLIENT_SET,
    "EVENT_MEATHOD":EVENT_MEATHOD,
    "ADMIN_PROMPT_SET":ADMIN_PROMPT_SET,
    "SU_PROMPT_SET":SU_PROMPT_SET,
    "INTERNET_ZONE_SET":INTERNET_ZONE_SET,
    "JAVA_PERMISSIONS_SET":JAVA_PERMISSIONS_SET,
    "DMA_SET":DMA_SET,
    "SSL_FALLBACK":SSL_FALLBACK,
    "DEFENDER_SET":DEFENDER_SET,
    "SMB_DRIVER":SMB_DRIVER,
    "ORACLE_REMEDIATION":ORACLE_REMEDIATION,
    "JOIN_MAPS":JOIN_MAPS,
    "SERVICE_SET":SERVICE_SET,
}